name: Bug Report
description: Report a bug
title: "[Bug]: "
labels: ["bug"]
assignees:
  - ena0
body:
  - type: markdown
    attributes:
      value: Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: textarea
    id: how
    attributes:
      label: how to redo the bug ?
      description: Tell us how to redo the bug
  - type: input
    id: version
    attributes: 
      label: What version do you use
      value: "v"
      
      
      
